version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-data:/root/.ollama
    restart: unless-stopped

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipeline
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MODELS_TO_PULL=${MODELS_TO_PULL}
      - FINETUNE_MODEL=${FINETUNE_MODEL}
      - TRAINING_DATA=${TRAINING_DATA}
      - S3_BUCKET=${S3_BUCKET}
      - SAGEMAKER_ROLE_ARN=${SAGEMAKER_ROLE_ARN}
      - DEBUG=${DEBUG}
      - CREATE_SAMPLE_DATA=true
    depends_on:
      - ollama
    volumes:
      - ./scripts:/app/scripts