version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  pipeline:
    build: .
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - S3_BUCKET=ollama-lora-pipeline
      - MODELS_TO_PULL=${MODELS_TO_PULL:-"llama2 mistral"}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-2
      # Uncomment to enable finetuning
      # - FINETUNE_MODEL=mistralai/Mistral-7B-v0.1
      # - TRAINING_DATA=s3://ollama-lora-pipeline/training-data/
    volumes:
      - ./models:/app/models

volumes:
  ollama_data: