version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Removed healthcheck

  pipeline:
    build: .
    depends_on:
      - ollama
    environment:
      - S3_BUCKET=ollama-lora-pipeline
      - MODELS_TO_PULL=${MODELS_TO_PULL:-"llama2 mistral"}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-2
      # Uncomment to enable finetuning
      # - FINETUNE_MODEL=mistralai/Mistral-7B-v0.1
      # - TRAINING_DATA=s3://ollama-lora-pipeline/training-data/
    volumes:
      - ./models:/app/models
    # Removed healthcheck

volumes:
  ollama_data: