---
name: Model Training Pipeline

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f "./requirements.txt" ]; then
            pip install -r ./requirements.txt
          else
            echo "ERROR: requirements.txt not found"
            exit 1
          fi

      - name: Run pipeline script
        run: |
          set -e
          echo "Starting model training pipeline..."

          if [ ! -f "./scripts/pipeline.sh" ]; then
            echo "ERROR: pipeline.sh script not found at ./scripts/pipeline.sh"
            exit 1
          fi

          if [ ! -f "./data/train.jsonl" ]; then
            echo "ERROR: Training data not found at ./data/train.jsonl"
            exit 1
          fi

          chmod +x ./scripts/pipeline.sh
          echo "Running pipeline with TinyLlama model and training data..."

          # Run pipeline with error handling
          if ! ./scripts/pipeline.sh \
               "TinyLlama/TinyLlama-1.1B-Chat-v1.0" \
               "./data/train.jsonl"; then
            echo "ERROR: Pipeline execution failed"
            echo "Please check the logs above for detailed error information"
            exit 1
          fi

          echo "Pipeline completed successfully!"
