name: Ollama Lora Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

env:
  AWS_REGION: us-east-1
  ECR_REPO_NAME: ollama-lora-sagemaker

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Debug: List repository contents
      run: |
        echo "--- Repository contents ---"
        ls -al "${{ github.workspace }}"
        echo "--- Checking Dockerfile ---"
        ls -al "${{ github.workspace }}/Dockerfile" || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      # Build using Dockerfile in repository root
      run: "docker build --no-cache -t ollama-lora-sagemaker ."

    - name: Test Docker image
      run: |
        echo "Testing Docker image..."
        docker run --rm ollama-lora-sagemaker echo "Docker image built successfully"

  finetune-model-1:
    runs-on: ubuntu-latest
    needs: build-docker-image # This job depends on the Docker image being built
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4 # Use this action for AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Verify AWS credentials
      run: |
        aws sts get-caller-identity
        echo "AWS credentials configured successfully"

    - name: Run fine-tuning pipeline for Model 1 on SageMaker
      run: |
        chmod +x scripts/pipeline.sh # Ensure execute permission
        scripts/pipeline.sh openlm-research/open_llama_3b data/train.jsonl

  finetune-model-2:
    runs-on: ubuntu-latest
    needs: build-docker-image # This job also depends on the Docker image being built
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4 # Use this action for AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Verify AWS credentials
      run: |
        aws sts get-caller-identity
        echo "AWS credentials configured successfully"

    - name: Run fine-tuning pipeline for Model 2 on SageMaker
      run: |
        chmod +x scripts/pipeline.sh # Ensure execute permission
        scripts/pipeline.sh distilbert-base-uncased data/train.jsonl
