name: Ollama Lora Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      # Added --no-cache to force a fresh build and ensure updated scripts are used
      # Corrected Dockerfile path to 'docker/Dockerfile'
      run: docker build --no-cache -t ollama-lora-sagemaker -f docker/Dockerfile .

  finetune-model-1:
    runs-on: ubuntu-latest
    needs: build-docker-image # This job depends on the Docker image being built
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4 # Use this action for AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Make sure this matches the region in pipeline.sh

    - name: Run fine-tuning pipeline for Model 1 on SageMaker
      run: |
        scripts/pipeline.sh openlm-research/open_llama_3b data/train.jsonl

  finetune-model-2:
    runs-on: ubuntu-latest
    needs: build-docker-image # This job also depends on the Docker image being built
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4 # Use this action for AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Make sure this matches the region in pipeline.sh

    - name: Run fine-tuning pipeline for Model 2 on SageMaker
      run: |
        scripts/pipeline.sh distilbert-base-uncased data/train.jsonl # Updated model name
