name: Ollama LoRA - Parallel Fine-Tuning

on:
  push:
    branches: [ main ]

jobs:
  train-multiple:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [
          "tiiuae/falcon-7b",
          "openlm-research/open_llama_3b"
        ]
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fine-tune and convert
      run: bash scripts/run_pipeline.sh "${{ matrix.model }}" "data/train.jsonl"
