name: Ollama Pipeline - Model Training and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: 
          - "openlm-research/open_llama_3b"
          - "distilbert-base-uncased"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Verify Dockerfile location
      run: |
        echo "--- Checking Dockerfile location ---"
        ls -la Dockerfile
        echo "--- Repository contents ---"
        ls -la
        echo "--- Scripts directory ---"
        ls -la scripts/
        echo "--- Data directory ---" 
        ls -la data/

    - name: Make pipeline script executable
      run: chmod +x scripts/pipeline.sh

    - name: Run complete pipeline for ${{ matrix.model }}
      run: |
        echo "Starting pipeline for model: ${{ matrix.model }}"
        scripts/pipeline.sh "${{ matrix.model }}" "data/train.jsonl"
      env:
        AWS_DEFAULT_REGION: us-east-1

    - name: Verify pipeline artifacts
      run: |
        echo "--- Checking for pipeline completion ---"
        aws s3 ls s3://ollama-lora-pipeline/gguf/ || echo "No GGUF files found"
        aws s3 ls s3://ollama-lora-pipeline/modelfiles/ || echo "No modelfiles found"
      continue-on-error: true

  notify-completion:
    runs-on: ubuntu-latest
    needs: build-and-train
    if: always()
    
    steps:
    - name: Pipeline completion status
      run: |
        if [ "${{ needs.build-and-train.result }}" == "success" ]; then
          echo "✅ Pipeline completed successfully for all models"
        else
          echo "❌ Pipeline failed for one or more models"
          exit 1
        fi