name: Ollama Pipeline with SageMaker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up environment
        run: |
          chmod +x setup.sh
          ./setup.sh
          chmod +x pipeline.sh
      
      - name: Build and run with Docker Compose
        run: |
          # Create ollama data directory
          mkdir -p ollama-data
          
          # Start Ollama service first
          docker compose up -d ollama
          
          # Give Ollama time to initialize
          echo "Waiting for Ollama to initialize..."
          sleep 30
          
          # Run the pipeline container
          docker compose up pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          MODELS_TO_PULL: "llama2 mistral"
          FINETUNE_MODEL: "mistralai/Mistral-7B-v0.1"
          TRAINING_DATA: "s3://ollama-lora-pipeline/training-data/"
          S3_BUCKET: "ollama-lora-pipeline"
          SAGEMAKER_ROLE_ARN: ${{ secrets.AWS_SAGEMAKER_ROLE_ARN }}
          DEBUG: "true"