name: Ollama Pipeline with SageMaker

on:
  push:
    branches: [ main, add-pipeline-with-sagemaker1 ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make script files executable
        run: |
          chmod +x pipeline.sh
          chmod +x extract_gguf.py
          chmod +x sagemaker_finetune.py
      
      - name: Build and run Docker Compose
        run: |
          docker-compose build
          docker-compose up -d ollama
          sleep 30  # Give Ollama time to initialize
          docker-compose up pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MODELS_TO_PULL: "llama2 mistral"